### ISSUE TITLE
Remove legacy ReactFlow workspace-related code

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/dashboards-flow-framework#155]
Recent UX changes changed the paradigm of persisting form data within a ReactFlow workspace -> persisting within a form component. As a consequence, there is a lot of legacy code that can be removed once the base refactoring of existing functionality is complete. This includes:
- refactoring the `component_types/` classes to be simplified and not contain form data. Many may be removed as well
- constants related to `component_types` no longer in use
- the entire `component_details` component once relevant code has been refactored elsewhere
- utility / conversion fns to convert between form <-> component data <-> workflow template no longer in use

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by ohltyler** [comment]
Been completed via several PRs over time. Resolving.
