### ISSUE TITLE
[MDS] Integrate plugin with multiple data sources

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/dashboards-flow-framework#215]
Onboard to OSD's multiple data source (MDS) feature. This will include:
- adding a data source picker to filter workflows by data source / cluster
- add some basic info per workflow on the UI indicating what data source it is coming from
- node API and backend API updates to optionally support the data-source-specific client if MDS is enabled. See work done in the [anomaly detection plugin](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin) as an example.

TODO: add screenshots of proposed UX mocks when available.

**Comment by saimedhi** [comment]
#228

**Comment by ohltyler** [comment]
Will use #228 instead.
