### ISSUE TITLE
[BUG]Missing dataSourceId in URL  When clicking Flow Framework from side nav

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/dashboards-flow-framework#275]
**What is the bug?**
  As stated in MDS feature addition PR [here](https://github.com/opensearch-project/dashboards-flow-framework/pull/274#issuecomment-2284686480), when clicking Flow Framework from side nav, dataSourceId is not retained in url. So, when page is refreshed as seen below, default datasource page is opened instead of current selected datasource. 
  
  Bug can be reproduced as below:
  [screen-capture (4).webm](https://github.com/user-attachments/assets/1daf95b0-32cc-4d10-b98c-935c7a92b689)

**What is the expected behavior?**

- When clicking Flow Framework from side nav, url should retain datasourceId.

**Comment by saimedhi** [comment]
- Issue also exists in https://github.com/opensearch-project/anomaly-detection-dashboards-plugin. 
- I'll check if this issue can be resolved within the plugin.

**Comment by ohltyler** [comment]
@saimedhi is this issue resolved?

**Comment by saimedhi** [comment]
> @saimedhi is this issue resolved?

No, I think this is a known issue in side nav implementation. Will connect with Zhou Su and confirm the same.

**Comment by ohltyler** [comment]
@saimedhi is this still a known issue?

**Comment by saimedhi** [comment]
- Yes Tyler, OSD Relavant issue is [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7171). I will try to fix this issue. 
- From discussion with Zhou Su, as flow framework do not have sub features in new left navigation. Fixing this issue is like an enhancement. Where plugins like AD,  Fixing this issue  is mandatory. Will work on this issue soon.

**Comment by saimedhi** [comment]
- **Updated Issue description** :  When clicking OpenSearch Flow from SideNav it always renders page with default data source. 
- It is not a functionality issue. I feel this issue can be closed. @SuZhou-Joe, I would like to know your thoughts. 
- Since, opensearch flow has single entry in SideNav. There is no reason to preserve datasourceId while clicking  opensearch flow from side Nav. 
- We will always be redirected to opensearch flow page with default datasourceId when clicking from sidenav. 
- Latest behavior is seen in the video [here](https://github.com/opensearch-project/dashboards-flow-framework/pull/447#issuecomment-2447821393) .

**Comment by ohltyler** [comment]
Closing if no issue. Reopen if needed.
