### ISSUE TITLE
[Enhancement] Add drill-down details for workflow-created resources

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/dashboards-flow-framework#378]
We currently display the associated resources created from a workflow. But, it would be even more helpful to drill down further into these resources, and view their individual configurations. For example, if a workflow creates an ingest pipeline, I may want to look at the pipeline config in a standalone way. Or, view some created index's generated mappings, or default settings. This can help in overall visibility, and let users decide if they want to override some defaults, or pass around those individual resource configs for deeper testing, etc.

The resources are visible in 2 places. Once on the workflow list page in the right-side flyout, and once under the "Resources" tab in the Tools panel in the workflow detail page:
<img width="1314" alt="Screenshot 2024-09-13 at 1 46 18 PM" src="https://github.com/user-attachments/assets/f1ef5ee6-cc29-4ca7-9ee8-2f859a2ca371">
<img width="696" alt="Screenshot 2024-09-13 at 1 46 30 PM" src="https://github.com/user-attachments/assets/ce272c03-74cb-4b95-9923-2f2eff33f7ca">

Ideally, we have some mechanism to click on those resources, or have a button somewhere, to pull up the resource details. Since we know the resource type and resource ID, we can execute the corresponding `GET` call to fetch such details. A few APIs may need to be added on the frontend to support this:
- get ingest pipeline API - https://opensearch.org/docs/latest/ingest-pipelines/get-ingest/#retrieving-information-about-a-specific-pipeline
- get search pipeline API - https://opensearch.org/docs/latest/search-plugins/search-pipelines/retrieving-search-pipeline/
- (maybe) variation of get index API. Depends on what we want to return (settings, mappings, both?)

**Comment by dblock** [comment]
[Catch All [Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta),  [3](https://github.com/krisfreedain),  [4](https://github.com/lukas-vlcek/)]

**Comment by ohltyler** [comment]
One idea is expanding detail in the table via expanding rows - see https://oui.opensearch.org/1.6/#/tabular-content/tables#expanding-rows
