### ISSUE TITLE
[BUG]DCO check is failing on Backport PRs

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/dashboards-flow-framework#399]
**What is the bug?**
DCO check is failing on Backport PRs. Need to debug and fix this issue. 

**How can one reproduce the bug?**
Example: https://github.com/opensearch-project/dashboards-flow-framework/pull/397/checks

**Comment by ohltyler** [comment]
This is consistent across all plugins, from my understanding there was no resolution. @opensearch-project/engineering-effectiveness is there any updates to this and/or tracking meta issue to address this?

**Comment by ohltyler** [comment]
Perfect! thanks Peter.

**Comment by peterzhuamazon** [comment]
Just to clarify we never see this in docs repo or project repo, so I assume this would help you fix it. 😄 
Let me know if there is any issue, I see there is a `-s` in the commit after cherry-pick in the latest code.

@ohltyler

**Comment by ohltyler** [comment]
> Just to clarify we never see this in docs repo or project repo, so I assume this would help you fix it. 😄 Let me know if there is any issue, I see there is a `-s` in the commit after cherry-pick in the latest code.
> 
> @ohltyler

Makes sense, we'll give it a shot 😄
