### ISSUE TITLE
[BUG]Unable to Navigate Back to Define Ingestion Pipeline After Skipping

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/dashboards-flow-framework#406]
**What is the bug?**
After selecting "Skip Ingestion Pipeline" and moving to the "Define Search Pipeline" step, there's no option to go back and define the ingestion pipeline. Can a button be added to allow users to return? Are there any challenges in implementing this?

Issue recording:

[screen-capture (19).webm](https://github.com/user-attachments/assets/6af7b5d3-d317-43ad-ac5d-67dab405abcf)

**Comment by ohltyler** [comment]
Good catch. Fixed in #407

**Comment by ohltyler** [comment]
Specifically https://github.com/opensearch-project/dashboards-flow-framework/pull/407/commits/705d663cdf76b66aadbfd1c32d3cfcf7bdba5a54
