### ISSUE TITLE
[BUG] Proposing removal of Side Nav present in the workflow list page.  

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/dashboards-flow-framework#444]
**What is the bug?**
- Proposing removal of Side Nav present in the workflow list page.  
- We don't have any navigation depending on that Side Nav. 
- This side nav is only visible on oldHomePage for workflows list page. 

**Do you have any screenshots?**
- proposing removal of Side nav present within the Flow Framework Dashboards Plugin. 
![Screenshot 2024-10-29 at 2 15 52 PM](https://github.com/user-attachments/assets/112bf83c-dc7d-47e1-b749-e2ce0215841d)

**Comment by saimedhi** [comment]
@Tyler please take a look

**Comment by ohltyler** [comment]
Thanks for opening! We still need to support old home page for now, but agreed we can navigate to it from breadcrumbs if in the child details page, and I agree maybe this can be removed pending we don't plan on having more navigation / pages on this plugin any time soon. @opensearch-project/opensearch-ux thoughts on this? Or @saimedhi please reach out to UX team to gain traction on this.

**Comment by kgcreative** [comment]
@ohltyler - This makes sense to me. If in the future we need to add more pages, we can flatten them under a category and list them in the main side nav. cc: @kamingleung

**Comment by saimedhi** [comment]
<img width="1352" alt="Screenshot 2024-10-29 at 4 12 23 PM" src="https://github.com/user-attachments/assets/87fefa36-4f9e-491d-8b54-ab0a8b2fef63">

**Comment by kamingleung** [comment]
@saimedhi I am aligned with removing the nav on both list, create, and Visual editor pages for the old look and feel.
