### ISSUE TITLE
[PROPOSAL] Rename repo to dashboards-flow-framework

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/dashboards-flow-framework#64]
Corresponding change needed in backend plugin: https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/168.

To follow https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#plugin-naming-conventions, we should prefix the repo name with `dashboards-`. With the backend plugin also changing to `flow-framework`, for consistency, we propose to change this to `dashboards-flow-framework`.

Further follow-ups to the plugin name in the source config files will be done later.

**Comment by ohltyler** [comment]
@opensearch-project/admin can you please help with this issue?

**Comment by peternied** [comment]
Renaming the repository is a one-way-door kind of change - @ohltyler could you see about getting 'lazy consensus' [1] on what the name is?  With that change agreed on you might want to reach out to #admin-requests channel if you need traction.

- [1] https://www.apache.org/foundation/how-it-works/#decision-making

**Comment by ohltyler** [comment]
We have gotten approval from @opensearch-project/admin to go ahead with the name change - this simply aligns the name with the proposed naming conventions already outlined, and has a small blast radius as it isn't onboarded into the OpenSearch build ecosystem yet.
